title: test-my-course
description: test
template:
  repo: my-ll-test-template
  name: my-ll-test-course
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
steps:
  - title: First step
    description: The first step in your course
    event: pull_request_review
    link: '{{ repoUrl }}'
    actions:
      - type: respond
        with: debug.md
        data:
          info: '%payload.pull_request.labels%'
      - type: gate
        required: false
        left: '%payload.pull_request.labels%'
        operator: test
        right: "bug"
        else:
          - type: respond
            with: uh-oh.md
            data:
              check: bug
      - type: gate
        required: false
        left: '%payload.pull_request.labels%'
        operator: test
        right: '"name":"bug"'
        else:
          - type: respond
            with: uh-oh.md
            data:
              check: 'name: bug'
              
          
tags: [
  "Beginner"
]
