title: test-my-course
description: test
template:
  repo: my-ll-test-template
  name: my-ll-test
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
steps:
  - title: First step
    description: The first step in your course
    event: pull_request_review
    link: '{{ repoUrl }}'
    actions:
      - type: respond
        with: debug.md
        data:
          info: '%payload.pull_request.labels%'
tags: [
  "Beginner"
]
