title: test-my-course
description: test
template:
  repo: my-ll-test-template
  name: my-ll-test-course
before:
  - type: createIssue
    title: Welcome
    body: new-issue.md
steps:
  - title: First step
    description: The first step in your course
    event: issue_comment
    link: '{{ repoUrl }}'
    actions:
      - type: respond
        issue: Welcome
        with: debug.md
        data:
          info: responding to Welcome without quotes
      - type: respond
        issue: "Welcome"
        with: debug.md
        data:
          info: responding to Welcome WITH quotes
      - type: gate
        left: '%payload.comment.body%'
        operator: ===
        right: hi
        else:
        - type: respond
          issue: Welcome
          with: debug.md
          data:
            info: responding to Welcome without quotes
        - type: respond
          issue: "Welcome"
          with: debug.md
          data:
            info: responding to Welcome WITH quotes
          
tags: [
  "Beginner"
]
